# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-10 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diputados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('turno', models.TextField()),
                ('comision', models.CharField(max_length=200)),
                ('resolutivos', models.TextField()),
                ('enlace', models.URLField()),
                ('diputado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diputados.Diputado')),
            ],
        ),
    ]
